services:
  backend:
    build: ./snapurl-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}

  frontend:
    build: ./snapurl-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend